export const fallbackCategories = [
  {
    "slug": "agendas",
    "name": "Agendas",
    "description": "Agenda tus días con intención y estilo."
  },
  {
    "slug": "planners",
    "name": "Planners",
    "description": "Organización flexible y visual para cada objetivo."
  },
  {
    "slug": "libretas",
    "name": "Libretas",
    "description": "Escribe, crea y documenta cada idea."
  },
  {
    "slug": "stickers",
    "name": "Stickers",
    "description": "Añade color y personalidad a tu rutina."
  },
  {
    "slug": "papeleria",
    "name": "Papelería",
    "description": "Pequeños esenciales con mucho encanto."
  },
  {
    "slug": "accesorios",
    "name": "Accesorios",
    "description": "Detalles prácticos para tu espacio."
  },
  {
    "slug": "regalos",
    "name": "Regalos",
    "description": "Obsequios cálidos y memorables."
  }
];

export const fallbackProducts = [
  {
    "id": 1,
    "name": "Agenda semanal",
    "slug": "agenda-semanal",
    "sku": "XIJ-001",
    "short_description": "Planifica tu semana con estilo y claridad.",
    "description": "Agenda semanal con distribución práctica para organizar objetivos, pendientes y citas. Ideal para quienes buscan una vista completa de cada semana.",
    "price": 500,
    "compare_at_price": 590.0,
    "stock": 25,
    "image_name": "agenda.svg",
    "category_name": "Agendas",
    "category_slug": "agendas",
    "rating": 4.8,
    "reviews_count": 13
  },
  {
    "id": 2,
    "name": "Agenda diaria",
    "slug": "agenda-diaria",
    "sku": "XIJ-002",
    "short_description": "Control detallado de cada día.",
    "description": "Agenda diaria pensada para jornadas intensas, con espacio generoso para tareas, notas y recordatorios importantes.",
    "price": 665,
    "compare_at_price": 784.7,
    "stock": 25,
    "image_name": "agenda.svg",
    "category_name": "Agendas",
    "category_slug": "agendas",
    "rating": 4.5,
    "reviews_count": 17
  },
  {
    "id": 3,
    "name": "Agenda citas",
    "slug": "agenda-citas",
    "sku": "XIJ-003",
    "short_description": "Perfecta para profesionales y servicios con agenda llena.",
    "description": "Agenda diseñada para organizar citas, bloques de atención y seguimiento de clientes de forma ordenada y elegante.",
    "price": 550,
    "compare_at_price": 649.0,
    "stock": 25,
    "image_name": "agenda.svg",
    "category_name": "Agendas",
    "category_slug": "agendas",
    "rating": 4.8,
    "reviews_count": 13
  },
  {
    "id": 4,
    "name": "Planner mini",
    "slug": "planner-mini",
    "sku": "XIJ-004",
    "short_description": "Pequeño en tamaño, grande en organización.",
    "description": "Planner compacto para llevar en bolsa o mochila, ideal para registrar metas, tareas rápidas y prioridades del día.",
    "price": 250,
    "compare_at_price": 295.0,
    "stock": 25,
    "image_name": "planner.svg",
    "category_name": "Planners",
    "category_slug": "planners",
    "rating": 4.8,
    "reviews_count": 8
  },
  {
    "id": 5,
    "name": "Agenda docentes",
    "slug": "agenda-docentes",
    "sku": "XIJ-005",
    "short_description": "Hecha para el ritmo de maestras y maestros.",
    "description": "Agenda especializada para docentes, útil para planear clases, actividades, evaluaciones y seguimiento académico.",
    "price": 520,
    "compare_at_price": 613.6,
    "stock": 25,
    "image_name": "agenda.svg",
    "category_name": "Agendas",
    "category_slug": "agendas",
    "rating": 4.2,
    "reviews_count": 10
  },
  {
    "id": 6,
    "name": "Agenda mini",
    "slug": "agenda-mini",
    "sku": "XIJ-006",
    "short_description": "La versión compacta para organizarte donde estés.",
    "description": "Agenda de formato reducido que conserva practicidad y diseño cálido para acompañarte todos los días.",
    "price": 350,
    "compare_at_price": 413.0,
    "stock": 25,
    "image_name": "agenda.svg",
    "category_name": "Agendas",
    "category_slug": "agendas",
    "rating": 5.0,
    "reviews_count": 13
  },
  {
    "id": 7,
    "name": "Agenda emprendedores",
    "slug": "agenda-emprendedores",
    "sku": "XIJ-007",
    "short_description": "Pensada para ideas, metas y seguimiento del negocio.",
    "description": "Agenda orientada a emprendedores que necesitan estructurar tareas, ventas, reuniones y objetivos semanales.",
    "price": 490,
    "compare_at_price": 578.2,
    "stock": 25,
    "image_name": "agenda.svg",
    "category_name": "Agendas",
    "category_slug": "agendas",
    "rating": 4.5,
    "reviews_count": 5
  },
  {
    "id": 8,
    "name": "Libreta hojas blancas",
    "slug": "libreta-hojas-blancas",
    "sku": "XIJ-008",
    "short_description": "Creatividad sin límites.",
    "description": "Libreta con hojas blancas ideal para escribir, bocetar, dibujar o documentar ideas con libertad total.",
    "price": 220,
    "compare_at_price": 259.6,
    "stock": 25,
    "image_name": "libreta.svg",
    "category_name": "Libretas",
    "category_slug": "libretas",
    "rating": 4.2,
    "reviews_count": 12
  },
  {
    "id": 9,
    "name": "Libreta hojas de raya",
    "slug": "libreta-hojas-de-raya",
    "sku": "XIJ-009",
    "short_description": "Para notas limpias y ordenadas.",
    "description": "Libreta rayada con formato clásico, excelente para apuntes, journaling, trabajo y estudio.",
    "price": 280,
    "compare_at_price": 330.4,
    "stock": 25,
    "image_name": "libreta.svg",
    "category_name": "Libretas",
    "category_slug": "libretas",
    "rating": 4.2,
    "reviews_count": 7
  },
  {
    "id": 10,
    "name": "Libreta journal",
    "slug": "libreta-journal",
    "sku": "XIJ-010",
    "short_description": "Tu espacio para hábitos, reflexiones y creatividad.",
    "description": "Libreta estilo journal para organizar pensamientos, registros personales, seguimiento de hábitos o planificación flexible.",
    "price": 310,
    "compare_at_price": 365.8,
    "stock": 25,
    "image_name": "libreta.svg",
    "category_name": "Libretas",
    "category_slug": "libretas",
    "rating": 4.8,
    "reviews_count": 8
  },
  {
    "id": 11,
    "name": "Libreta chica",
    "slug": "libreta-chica",
    "sku": "XIJ-011",
    "short_description": "Práctica y ligera para llevar a todos lados.",
    "description": "Libreta compacta para notas rápidas, pendientes y recordatorios cotidianos.",
    "price": 140,
    "compare_at_price": 165.2,
    "stock": 25,
    "image_name": "libreta.svg",
    "category_name": "Libretas",
    "category_slug": "libretas",
    "rating": 4.5,
    "reviews_count": 13
  },
  {
    "id": 12,
    "name": "Libreta chica crema",
    "slug": "libreta-chica-crema",
    "sku": "XIJ-012",
    "short_description": "Pequeña, cálida y con papel suave a la vista.",
    "description": "Libreta pequeña con hojas tono crema que aporta una experiencia visual agradable y elegante al escribir.",
    "price": 125,
    "compare_at_price": 147.5,
    "stock": 25,
    "image_name": "libreta.svg",
    "category_name": "Libretas",
    "category_slug": "libretas",
    "rating": 4.8,
    "reviews_count": 10
  },
  {
    "id": 13,
    "name": "Libreta mini",
    "slug": "libreta-mini",
    "sku": "XIJ-013",
    "short_description": "La libreta más portable del catálogo.",
    "description": "Formato mini perfecto para listas rápidas, notas breves o detalles que no se te pueden escapar.",
    "price": 45,
    "compare_at_price": 53.1,
    "stock": 25,
    "image_name": "libreta.svg",
    "category_name": "Libretas",
    "category_slug": "libretas",
    "rating": 4.8,
    "reviews_count": 8
  },
  {
    "id": 14,
    "name": "Libreta cosida",
    "slug": "libreta-cosida",
    "sku": "XIJ-014",
    "short_description": "Sencilla, resistente y encantadora.",
    "description": "Libreta cosida con acabado artesanal, ideal para uso diario y proyectos personales.",
    "price": 80,
    "compare_at_price": 94.4,
    "stock": 25,
    "image_name": "libreta.svg",
    "category_name": "Libretas",
    "category_slug": "libretas",
    "rating": 5.0,
    "reviews_count": 2
  },
  {
    "id": 15,
    "name": "Libreta post it",
    "slug": "libreta-post-it",
    "sku": "XIJ-015",
    "short_description": "Notas adhesivas siempre a la mano.",
    "description": "Formato funcional para quienes aman marcar ideas, pendientes y mensajes rápidos con practicidad.",
    "price": 65,
    "compare_at_price": 76.7,
    "stock": 25,
    "image_name": "libreta.svg",
    "category_name": "Libretas",
    "category_slug": "libretas",
    "rating": 4.2,
    "reviews_count": 17
  },
  {
    "id": 16,
    "name": "Libreta post it chica",
    "slug": "libreta-post-it-chica",
    "sku": "XIJ-016",
    "short_description": "Versión compacta para notas rápidas.",
    "description": "Una libreta pequeña y funcional para acompañar tu día con recordatorios inmediatos y visibles.",
    "price": 45,
    "compare_at_price": 53.1,
    "stock": 25,
    "image_name": "libreta.svg",
    "category_name": "Libretas",
    "category_slug": "libretas",
    "rating": 4.2,
    "reviews_count": 7
  },
  {
    "id": 17,
    "name": "Adventure book",
    "slug": "adventure-book",
    "sku": "XIJ-017",
    "short_description": "Guarda recuerdos, viajes e historias especiales.",
    "description": "Libro de aventuras para documentar experiencias, fotos, memorias y momentos inolvidables.",
    "price": 500,
    "compare_at_price": 590.0,
    "stock": 25,
    "image_name": "regalo.svg",
    "category_name": "Regalos",
    "category_slug": "regalos",
    "rating": 4.8,
    "reviews_count": 17
  },
  {
    "id": 18,
    "name": "Tarjetas",
    "slug": "tarjetas",
    "sku": "XIJ-018",
    "short_description": "Pequeños mensajes con gran intención.",
    "description": "Tarjetas versátiles para regalos, agradecimientos, notas especiales o detalles creativos.",
    "price": 30,
    "compare_at_price": 35.4,
    "stock": 25,
    "image_name": "papeleria.svg",
    "category_name": "Papelería",
    "category_slug": "papeleria",
    "rating": 4.5,
    "reviews_count": 6
  },
  {
    "id": 19,
    "name": "Juego",
    "slug": "juego",
    "sku": "XIJ-019",
    "short_description": "Un producto divertido para compartir.",
    "description": "Juego pensado para momentos de convivencia, ideal como regalo creativo y memorable.",
    "price": 290,
    "compare_at_price": 342.2,
    "stock": 25,
    "image_name": "regalo.svg",
    "category_name": "Regalos",
    "category_slug": "regalos",
    "rating": 4.2,
    "reviews_count": 9
  },
  {
    "id": 20,
    "name": "Portaretratos",
    "slug": "portaretratos",
    "sku": "XIJ-020",
    "short_description": "Tus recuerdos favoritos en un lugar especial.",
    "description": "Portarretratos decorativo para exhibir fotos y darle calidez a cualquier espacio.",
    "price": 280,
    "compare_at_price": 330.4,
    "stock": 25,
    "image_name": "accesorio.svg",
    "category_name": "Accesorios",
    "category_slug": "accesorios",
    "rating": 4.5,
    "reviews_count": 6
  },
  {
    "id": 21,
    "name": "Stickers Planilla",
    "slug": "stickers-planilla",
    "sku": "XIJ-021",
    "short_description": "Organiza con color y personalidad.",
    "description": "Planilla de stickers para planners, agendas y libretas. Perfecta para destacar tareas y eventos.",
    "price": 40,
    "compare_at_price": 47.2,
    "stock": 25,
    "image_name": "stickers.svg",
    "category_name": "Stickers",
    "category_slug": "stickers",
    "rating": 4.8,
    "reviews_count": 12
  },
  {
    "id": 22,
    "name": "Stickers 10 pack",
    "slug": "stickers-10-pack",
    "sku": "XIJ-022",
    "short_description": "Más variedad para decorar tu organización.",
    "description": "Paquete de 10 stickers para personalizar tus productos de papelería con estilo.",
    "price": 35,
    "compare_at_price": 41.3,
    "stock": 25,
    "image_name": "stickers.svg",
    "category_name": "Stickers",
    "category_slug": "stickers",
    "rating": 4.2,
    "reviews_count": 8
  },
  {
    "id": 23,
    "name": "Organizador escritorio",
    "slug": "organizador-escritorio",
    "sku": "XIJ-023",
    "short_description": "Todo en su lugar, sobre tu mesa.",
    "description": "Organizador de escritorio para mantener útiles, notas y accesorios siempre ordenados y a la vista.",
    "price": 365,
    "compare_at_price": 430.7,
    "stock": 25,
    "image_name": "accesorio.svg",
    "category_name": "Accesorios",
    "category_slug": "accesorios",
    "rating": 4.5,
    "reviews_count": 5
  },
  {
    "id": 24,
    "name": "Planner carta",
    "slug": "planner-carta",
    "sku": "XIJ-024",
    "short_description": "Espacio amplio para una planeación completa.",
    "description": "Planner tamaño carta para visualizar objetivos, tareas y actividades con más comodidad.",
    "price": 220,
    "compare_at_price": 259.6,
    "stock": 25,
    "image_name": "planner.svg",
    "category_name": "Planners",
    "category_slug": "planners",
    "rating": 4.8,
    "reviews_count": 8
  },
  {
    "id": 25,
    "name": "Planner media carta",
    "slug": "planner-media-carta",
    "sku": "XIJ-025",
    "short_description": "Balance perfecto entre tamaño y practicidad.",
    "description": "Planner media carta ideal para quienes necesitan planear sin cargar demasiado volumen.",
    "price": 140,
    "compare_at_price": 165.2,
    "stock": 25,
    "image_name": "planner.svg",
    "category_name": "Planners",
    "category_slug": "planners",
    "rating": 4.5,
    "reviews_count": 8
  },
  {
    "id": 26,
    "name": "Separadores de imán",
    "slug": "separadores-de-iman",
    "sku": "XIJ-026",
    "short_description": "Marca tus páginas favoritas con estilo.",
    "description": "Separadores imantados funcionales y bonitos para agendas, libros y libretas.",
    "price": 60,
    "compare_at_price": 70.8,
    "stock": 25,
    "image_name": "papeleria.svg",
    "category_name": "Papelería",
    "category_slug": "papeleria",
    "rating": 5.0,
    "reviews_count": 6
  },
  {
    "id": 27,
    "name": "Calendario Refri",
    "slug": "calendario-refri",
    "sku": "XIJ-027",
    "short_description": "Organización visible para toda la casa.",
    "description": "Calendario para refrigerador, ideal para tareas, menús, pendientes y recordatorios familiares.",
    "price": 40,
    "compare_at_price": 47.2,
    "stock": 25,
    "image_name": "papeleria.svg",
    "category_name": "Papelería",
    "category_slug": "papeleria",
    "rating": 4.8,
    "reviews_count": 13
  },
  {
    "id": 28,
    "name": "Planner mensual",
    "slug": "planner-mensual",
    "sku": "XIJ-028",
    "short_description": "Visualiza el mes de un vistazo.",
    "description": "Planner mensual para objetivos, eventos y seguimiento general de actividades importantes.",
    "price": 140,
    "compare_at_price": 165.2,
    "stock": 25,
    "image_name": "planner.svg",
    "category_name": "Planners",
    "category_slug": "planners",
    "rating": 4.8,
    "reviews_count": 13
  }
];
